#ifndef CONFIG_H
#define CONFIG_H

#include "constants.h"
#define DEFAULT_BASE_ADRESS (HIRES_SCREEN_ADDRESS + 40*((VIEWPORT_START_LINE<<1) + VIEWPORT_START_LINE) + (VIEWPORT_START_COLUMN>>1))

//#define USE_C_VIEWPORT
// #define USE_C_COLORRIGHTTEXEL
// #define USE_C_COLORLEFTTEXEL
// #define USE_SLOW_TEXEL
#define __USE_C_DDA__
#endif // CONFIG_H