//
// Floppy layout generated by FloppyBuilder 1.2
//

#ifdef ASSEMBLER
//
// Information for the Assembler
//
#ifdef LOADER
FileStartSector .byt 135,133,8,142,139
FileStartTrack .byt 0,1,1,1,3
FileSizeLow .byt <6558,<760,<1536,<32768,<32768
FileSizeHigh .byt >6558,>760,>1536,>32768,>32768
#undef LOADER
#endif // LOADER
#undef ASSEMBLER
#else
//
// Information for the Compiler
//
#endif

//
// Summary for this floppy building session:
//
#define FLOPPY_SIDE_NUMBER 2    // Number of sides
#define FLOPPY_TRACK_NUMBER 42    // Number of tracks
#define FLOPPY_SECTOR_PER_TRACK 17   // Number of sectors per track

#define FLOPPY_LOADER_TRACK 0   // Track where the loader is stored
#define FLOPPY_LOADER_SECTOR 4   // Sector where the loader is stored
#define FLOPPY_LOADER_ADDRESS 64768   // Address where the loader is loaded on boot ($fd00)

//
// List of files written to the floppy
//
// Entry #0 '..\build\files\Main.o'
// - Starts on  track 0 sector 7 and is 15 sectors long (3814 compressed bytes: 58% of 6558 bytes).
// Entry #1 '..\build\files\Font6x8.hir'
// - Starts on  track 1 sector 5 and is 3 sectors long (556 compressed bytes: 73% of 760 bytes).
// Entry #2 'Reserved sectors'
// - Starts on  track 1 sector 8 and is 6 sectors long (1536 bytes).
// Entry #3 '..\build\files\pano_02.vrb'
// - Starts on  track 1 sector 14 and is 31 sectors long (7815 compressed bytes: 23% of 32768 bytes).
// Entry #4 '..\build\files\pano_01.vrb'
// - Starts on  track 3 sector 11 and is 19 sectors long (4807 compressed bytes: 14% of 32768 bytes).
//
// 80 sectors used, out of 1428. (5% of the total disk size used)
//
#define LOADER_SECTOR_BUFFER $200
#define LOADER_BASE_ZERO_PAGE $F2
#define LOADER_GAME_PROGRAM 0
#define LOADER_GAME_PROGRAM_ADDRESS $C000
#define LOADER_GAME_PROGRAM_TRACK 0
#define LOADER_GAME_PROGRAM_SECTOR 135
#define LOADER_GAME_PROGRAM_SIZE 6558
#define LOADER_GAME_PROGRAM_SIZE_COMPRESSED 3814
#define LOADER_FONT_6x8 1
#define LOADER_PANO_02 3
#define LOADER_PANO_01 4

//
// Metadata
//
#ifdef METADATA_STORAGE

#endif // METADATA_STORAGE

